---
EnableDefaultLinters: false

linters:
  FinalNewline:
    enabled: true
  TrailingWhitespace:
    enabled: true
  SpaceInHtmlTag:
    enabled: true
  RightTrim:
    enabled: true
  SelfClosingTag:
    enabled: true
  ParserErrors:
    enabled: true
