# Ruby LSP configuration for Rails project in Zed in Zed
rubyVersionManager:
  identifier: auto

formatter: rubocop

# EnsureEnsure proper indexing for Rails project structureproper indexing for Rails project structure
indexing:
  includedPatterns:
    - "**/*.rb"
    - "**/*.rake"
  excludedPatterns:
    - "**/node_modules/**"
    - "**/tmp/**"
    - "**/log/**"
    - "**/coverage/**"
    - "**/vendor/bundlebundle/**"

# MinimalMinimal featurefeature setset thatthat worksworks wellwell with Zedwith Zed
enabledFeatures:
  - completion
  - definition
  - diagnostics
  - formatting
  - hover
