# Name of your application. Used to uniquely configure containers.
service: f2

# Name of the container image.
image: dreikanter/f2

# Require an explicit deployment destination, e.g. `bin/kamal deploy -d staging`.
require_destination: true

# Credentials for your image host.
registry:
  # Specify the registry server, if you're not using Docker Hub
  server: ghcr.io
  username: dreikanter

  # Always use an access token rather than real password when possible.
  password:
    - KAMAL_REGISTRY_PASSWORD

# Environment variables shared by all destinations.
env:
  clear:
    APP_REVISION: <%= `git rev-parse HEAD`.strip %>
    APP_REVISION_SHORT: <%= `git rev-parse --short HEAD`.strip %>
    APP_DEPLOYED_AT: <%= `date -u +%Y-%m-%dT%H:%M:%SZ`.strip %>
  secret:
    - RAILS_MASTER_KEY
    - POSTGRES_PASSWORD

# Aliases are triggered with "bin/kamal <alias>". You can overwrite arguments on invocation:
# "bin/kamal logs -r jobs" will tail logs from the first server in the jobs section.
aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole"

# Bridge fingerprinted assets, like JS and CSS, between versions to avoid
# hitting 404 on in-flight requests. Combines all files from new and old
# version inside the asset_path.
asset_path: /rails/public/assets

# Configure the image builder.
builder:
  arch: amd64

  # # Build image via remote server (useful for faster amd64 builds on arm64 computers)
  # remote: ssh://docker@docker-builder-server
  #
  # # Pass arguments and secrets to the Docker build process
  # args:
  #   RUBY_VERSION: 4.0.3
  # secrets:
  #   - GITHUB_TOKEN
  #   - RAILS_MASTER_KEY
# Use a different ssh user than root
# ssh:
#   user: app
