name: Debug RuboCop

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Run RuboCop
        run: |
          set +e
          bin/rubocop -f simple > rubocop.log 2>&1
          status=$?
          cat rubocop.log
          exit $status

      - name: Upload RuboCop report
        if: always()
        uses: actions/upload-artifact@v6
        with:
          name: rubocop-report
          path: rubocop.log
